language: node_js

node_js:
  - "4"
  - "6"
  - "8"
  - "10"
  - "12"

before_install:
  - echo $TRAVIS_NODE_VERSION
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      if [[ $(node -v) =~ v[1-9][0-9] ]]; then
        export PGUSER="postgres";
        export PGDATABASE="postgres";
        export PGSSLMODE="allow";
      else
        export PGUSER="postgres";
        export PGDATABASE="postgres";
        export PGSSLMODE="prefer";
      fi
    fi
  - nvm --version
  - node --version
  - npm --version

env:
  - CC=clang CXX=clang++ npm_config_clang=1
